on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - gh5-pipeline
    - main
    tags: 
    - 'v*'

jobs:

  ############################################################
  ############################################################
  # Runs tests

  test: 
    runs-on: ubuntu-latest
    steps:

    ############################################################
    ############################################################
    # Checkout code and install dependencies

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    ############################################################
    ############################################################
    # Perform linting

    - name: Run linter
      run: npm run eslint
