on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags: 
    - 'v*'

jobs:


  ######################################################################
  ######################################################################
  # Run tests

  test: 
    runs-on: ubuntu-latest
    steps:

    ##################################################
    # Checkout code and install dependencies

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    ##################################################
    # Perform linting

    - name: Run linter
      run: npm run eslint


  ######################################################################
  ######################################################################
  # Build application and installer

  build:
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test]
    steps:

    ##################################################
    # Checkout code and install dependencies

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    ##################################################
    # Build installer

    - name: Build installer
      run: npm run build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
